version: "3.8"

services:
  php:
    image: amp:latest
    container_name: damp-server
    hostname: damp
    domainname: damp.doc
    ports:
      - 8080:80
      - 465:465
    volumes:
      - ./local/www:/var/www/html/
      - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf

  mysql:
    image: mysql:8.0.31
    container_name: "damp_mysql"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./local/mysql:/var/lib/mysql
      - ./local/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "damp_phpmyadmin"
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8081:80
    volumes:
      - ./local/sessions:/sessions
